services:
  mcserverstatbot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mcserverstatbot
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "8080:8080"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
